In [139]:
import pandas as pd
import numpy as np

In [140]:
# Load dog_mix_breed csv.
dog_mix_breed = pd.read_csv("dog_mix_breed.csv")
dog_mix_breed.head()

                                  breed
0                Papillon/Border Collie
1        Chihuahua Shorthair/Pomeranian
2  Miniature Schnauzer/Miniature Poodle
3    German Shepherd/Labrador Retriever
4   Cardigan Welsh Corgi/English Setter

In [141]:
#Load dog_features2 csv. 
dog_features = pd.read_csv("doggy_features2.csv")
dog_features.head()

,Breed,Spinone-Italiano,Dachshund,Shetland-Sheepdog,Labrador-Retriever,Miniature-Schnauzer,Lhasa-Apso,Border-Collie,German-Shepherd,Newfoundland,...,Welsh-Springer-Spaniel,Samoyed,Greater-Swiss-Mountain-Dog,Gordon-Setter,English-Cocker-Spaniel,Irish-Setter,Lowchen,Neapolitan-Mastiff,Norwegian-Elkhound,Lakeland-Terrier
0,Energy Level,3,4,3,4,3,3,5,3,2,...,3,3,2,4,3,5,4,2,4,4
1,Exercise Requirements,3,2,3,3,3,2,5,4,2,...,3,3,3,4,3,5,1,1,3,3
2,Playfulness,3,3,3,5,4,3,4,2,3,...,3,4,2,3,4,5,3,1,4,5
3,Affection Level,4,3,3,5,4,3,3,3,5,...,4,4,3,4,5,5,3,4,3,3
4,Friendliness to Dogs,3,3,4,4,3,2,3,1,4,...,3,3,3,2,5,3,4,1,2,1

In [142]:
# Remove "_" in each dog breed. 
features_columns=dog_features.columns
dog_features.columns=features_columns.str.replace('-',' ')

In [143]:
# Swapping dag_features
dog_features_swapped= dog_features.T

In [144]:
# Deal with Header
dog_features_swapped.columns=dog_features_swapped.iloc[0,:]
dog_features_swapped=dog_features_swapped.drop("Breed")
dog_features_swapped.head()

Breed,Energy Level,Exercise Requirements,Playfulness,Affection Level,Friendliness to Dogs,Friendliness to Other Pets,Friendliness to Strangers,Watchfulness,Ease of Training,Grooming Requirements,Heat Sensitivity,Vocality
Spinone Italiano,3,3,3,4,3,4,4,1,3,2,3,4
Dachshund,4,2,3,3,3,2,1,2,2,2,3,5
Shetland Sheepdog,3,3,3,3,4,4,1,1,5,4,3,5
Labrador Retriever,4,3,5,5,4,5,5,2,5,2,3,4
Miniature Schnauzer,3,3,4,4,3,3,3,1,3,3,3,5

In [145]:
# Make a copy of dog_features_list columns 
dog_features_list=dog_features_swapped.index.to_list()
dog_features_swapped_columns=dog_features_swapped.columns.to_list()

In [146]:
# Add dog_features_list columns to dog_mix_breed
for column in dog_features_swapped_columns:
    dog_mix_breed[str(column)] = ""
dog_mix_breed.head()

,breed,Energy Level,Exercise Requirements,Playfulness,Affection Level,Friendliness to Dogs,Friendliness to Other Pets,Friendliness to Strangers,Watchfulness,Ease of Training,Grooming Requirements,Heat Sensitivity,Vocality
0,Papillon/Border Collie,,,,,,,,,,,,
1,Chihuahua Shorthair/Pomeranian,,,,,,,,,,,,
2,Miniature Schnauzer/Miniature Poodle,,,,,,,,,,,,
3,German Shepherd/Labrador Retriever,,,,,,,,,,,,
4,Cardigan Welsh Corgi/English Setter,,,,,,,,,,,,

In [147]:
# For loop to calculate the mix breed features (Average of breeds in mix breeds)
for i in range(0,len(dog_mix_breed)):
    mylist=[]
    for breed in dog_features_list:
        if dog_mix_breed.iloc[i].str.contains(str(breed))[0]==True:
            mylist.append(breed)

    n=0
    for column in dog_features_swapped_columns:        
        dog_mix_breed[column][i]=dog_features_swapped[dog_features_swapped.index.isin(mylist)].iloc[:,n].mean()
        n+=1
dog_mix_breed.tail()

,breed,Energy Level,Exercise Requirements,Playfulness,Affection Level,Friendliness to Dogs,Friendliness to Other Pets,Friendliness to Strangers,Watchfulness,Ease of Training,Grooming Requirements,Heat Sensitivity,Vocality
1568,Whippet/German Shepherd,3,3.5,2.5,3.5,3,3.5,2.5,3,4,1.5,3,4.5
1569,Domestic Medium Hair/Manx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1570,Border Collie/Australian Kelpie,5,5,4,3,3,1,2,3,5,3,3,4
1571,Standard Schnauzer/German Shepherd,3.5,3.5,2.5,2.5,1.5,3,1.5,5,4,3,3,5
1572,Cardigan Welsh Corgi/Miniature Schnauzer,3,3,3.5,3.5,2.5,3.5,3,2.5,3.5,2,3,5

In [148]:
dog_features_swapped2=dog_features_swapped
#dog_features_swapped2.to_csv("dog_features_swapped2.csv")
dog_features_swapped2.insert(loc=0, column='breed', value=dog_features_swapped2.index)
#dog_features_swapped2.reset_index()
dog_features_swapped2.head()

Breed,breed,Energy Level,Exercise Requirements,Playfulness,Affection Level,Friendliness to Dogs,Friendliness to Other Pets,Friendliness to Strangers,Watchfulness,Ease of Training,Grooming Requirements,Heat Sensitivity,Vocality
Spinone Italiano,Spinone Italiano,3,3,3,4,3,4,4,1,3,2,3,4
Dachshund,Dachshund,4,2,3,3,3,2,1,2,2,2,3,5
Shetland Sheepdog,Shetland Sheepdog,3,3,3,3,4,4,1,1,5,4,3,5
Labrador Retriever,Labrador Retriever,4,3,5,5,4,5,5,2,5,2,3,4
Miniature Schnauzer,Miniature Schnauzer,3,3,4,4,3,3,3,1,3,3,3,5

In [149]:
dog_mix_breed_backup=dog_mix_breed
#dog_mix_breed_backup.reset_index(drop=True, inplace=True)
#dog_mix_breed_backup.to_csv("dog_mix_breed3.csv")
dog_mix_breed_backup.tail()

,breed,Energy Level,Exercise Requirements,Playfulness,Affection Level,Friendliness to Dogs,Friendliness to Other Pets,Friendliness to Strangers,Watchfulness,Ease of Training,Grooming Requirements,Heat Sensitivity,Vocality
1568,Whippet/German Shepherd,3,3.5,2.5,3.5,3,3.5,2.5,3,4,1.5,3,4.5
1569,Domestic Medium Hair/Manx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1570,Border Collie/Australian Kelpie,5,5,4,3,3,1,2,3,5,3,3,4
1571,Standard Schnauzer/German Shepherd,3.5,3.5,2.5,2.5,1.5,3,1.5,5,4,3,3,5
1572,Cardigan Welsh Corgi/Miniature Schnauzer,3,3,3.5,3.5,2.5,3.5,3,2.5,3.5,2,3,5

In [150]:
# Concat two csv.
all_dog_breed = pd.concat([dog_mix_breed_backup, dog_features_swapped2])

In [151]:
all_dog_breed.shape

(1693, 13)

In [152]:
#Reset index
all_dog_breed.reset_index().drop(columns='index')

Breed,breed,Energy Level,Exercise Requirements,Playfulness,Affection Level,Friendliness to Dogs,Friendliness to Other Pets,Friendliness to Strangers,Watchfulness,Ease of Training,Grooming Requirements,Heat Sensitivity,Vocality
0,Papillon/Border Collie,4.5,3,4.5,4,3.5,2.5,3,2,5,3,3,4.5
1,Chihuahua Shorthair/Pomeranian,4,1,4,1,1,3,1,1,1,3,3,5
2,Miniature Schnauzer/Miniature Poodle,3.5,3,4.5,4,3.5,3,3.5,1,4,4,3,5
3,German Shepherd/Labrador Retriever,3.5,3.5,3.5,4,2.5,4,3.5,3.5,5,2,3,4.5
4,Cardigan Welsh Corgi/English Setter,3.5,3.5,3,3.5,2.5,4,4,3,3.5,2,3,4.5
5,Australian Shepherd/Australian Cattle Dog,4.5,5,4.5,4,3,2.5,2,4,5,2.5,3,5
6,Basenji/Chihuahua Longhair,4,3,3,3,2,1,3,1,2,1,3,5
7,Siberian Husky/German Shepherd,3,4,3,3.5,2,3,3.5,3,3,2.5,4,4
8,German Shepherd/Boxer,4,3.5,3.5,4,2,3,2.5,5,4,1.5,4,4
9,Labrador Retriever/German Shepherd,3.5,3.5,3.5,4,2.5,4,3.5,3.5,5,2,3,4.5
10,German Shepherd/Chow Chow,2,3,1.5,2.5,1,3,1.5,4.5,3,2.5,4,5
11,Pit Bull/Labrador Retriever,4,3,5,5,4,5,5,2,5,2,3,4
12,Beagle/Chihuahua Longhair,3,3,4,5,5,5,5,1,1,1,3,4
13,Parson Russell Terrier/Chihuahua Shorthair,5,4,5,3,2,1,3,2,3,3,3,5
14,Catahoula/Labrador Retriever,4,3,5,5,4,5,5,2,5,2,3,4
15,Chihuahua Shorthair/Dachshund,4,2,3,3,3,2,1,2,2,2,3,5
16,Boxer/Pit Bull,5,3,5,5,3,3,3,5,3,1,5,3
17,Boxer/Labrador Retriever,4.5,3,5,5,3.5,4,4,3.5,4,1.5,4,3.5
18,Chihuahua Shorthair/Cardigan Welsh Corgi,3,3,3,3,2,4,3,4,4,1,3,5
19,German Shepherd/Pembroke Welsh Corgi,3,3.5,2.5,3.5,2,3.5,3,4.5,4.5,1.5,3,5
20,Beagle/Pug,3,2.5,4,4.5,4,4,3.5,1,2,1.5,4,4.5
21,Pointer/Labrador Retriever,4,3.5,4.5,4.5,4,4.5,4,2.5,4,1.5,3,4
22,Pembroke Welsh Corgi/Australian Cattle Dog,4,4,3.5,4,3,3,3,4,4.5,1.5,3,5
23,Bulldog/Australian Cattle Dog,3,3,4,4.5,2,3,3,3,3.5,2,4,3
24,Manchester Terrier/Beagle,3,3,4,5,5,5,5,1,1,1,3,4
25,Labrador Retriever/Pit Bull,4,3,5,5,4,5,5,2,5,2,3,4
26,Labrador Retriever/Border Collie,4.5,4,4.5,4,3.5,3,3.5,2.5,5,2.5,3,4
27,Rottweiler/Labrador Retriever,3.5,3,3.5,3.5,2.5,3.5,3,3.5,4,1.5,3.5,4.5
28,Collie Smooth/Labrador Retriever,4,3,5,5,4,5,5,2,5,2,3,4
29,Australian Shepherd/Border Collie,4.5,5,4.5,3.5,3,2,2,3.5,5,3,3,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1663,Saluki,2,3,3,3,3,3,1,2,3,2,3,3
1664,Bloodhound,3,3,1,5,3,5,3,1,1,1,4,4
1665,Leonberger,2,3,3,4,3,4,4,4,4,4,4,5
1666,Nova Scotia Duck Tolling Retriever,5,5,5,5,5,5,3,2,4,2,3,2
1667,German Pinscher,4,3,4,4,2,1,2,3,3,1,2,5
1668,Ibizan Hound,3,3,3,2,4,3,3,1,2,2,3,4
1669,Affenpinscher,4,3,4,4,3,3,3,1,3,4,4,5
1670,Japanese Chin,3,1,4,5,4,4,5,1,3,3,4,5
1671,Welsh Terrier,3,3,3,3,3,1,1,1,1,4,3,5
1672,Skye Terrier,2,2,3,4,1,1,1,1,3,3,4,5
1673,English Setter,4,4,3,4,3,4,5,2,3,3,3,4
1674,Old English Sheepdog,3,3,3,5,3,5,4,3,2,4,4,3
1675,Havanese,4,3,5,5,4,4,5,1,4,3,3,4
1676,Pharaoh Hound,3,4,3,3,4,2,2,1,3,1,3,4
1677,Bearded Collie,4,4,4,4,3,3,3,2,3,4,3,4
1678,French Bulldog,3,1,3,3,3,4,1,1,2,1,5,3
1679,Canaan Dog,3,4,3,3,3,4,2,3,4,1,3,5
1680,Irish Wolfhound,1,3,1,3,3,3,3,2,2,3,5,3
1681,Coton De Tulear,4,2,4,5,5,5,5,1,4,5,3,2
1682,Belgian Sheepdog,4,5,4,4,3,3,1,5,5,3,3,5
1683,Welsh Springer Spaniel,3,3,3,4,3,3,2,2,3,3,3,4
1684,Samoyed,3,3,4,4,3,5,4,1,2,3,5,5
1685,Greater Swiss Mountain Dog,2,3,2,3,3,4,2,3,4,1,4,4
1686,Gordon Setter,4,4,3,4,2,4,2,3,3,3,3,4
1687,English Cocker Spaniel,3,3,4,5,5,5,4,2,4,3,3,4
1688,Irish Setter,5,5,5,5,3,3,5,1,3,3,3,4
1689,Lowchen,4,1,3,3,4,4,3,1,3,4,3,4
1690,Neapolitan Mastiff,2,1,1,4,1,2,1,5,2,2,5,5
1691,Norwegian Elkhound,4,3,4,3,2,2,4,2,3,2,4,3
1692,Lakeland Terrier,4,3,5,3,1,1,1,1,1,4,3,5

In [153]:
# Check and dropna.
all_dog_breed.isna().sum()

Breed
breed                           0
Energy Level                  133
Exercise Requirements         133
Playfulness                   133
Affection Level               133
Friendliness to Dogs          133
Friendliness to Other Pets    133
Friendliness to Strangers     133
Watchfulness                  133
Ease of Training              133
Grooming Requirements         133
Heat Sensitivity              133
Vocality                      133
dtype: int64

In [155]:
all_dog_breed.dropna(inplace=True)

In [156]:
all_dog_breed.shape

(1560, 13)

In [158]:
#Export CSV.
all_dog_breed.to_csv("all_dog_breed.csv")